name = "backend"
compatibility_date = "2024-09-22"
compatibility_flags = [ "nodejs_compat" ]

# imaginative lilac pup accelerate
[vars]
DATABASE_URL = "DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNTgwNTY0MGItZDA3YS00MTc1LTk0NmQtMzk5NDIzZTY2MGQ1IiwidGVuYW50X2lkIjoiN2UzYTIyMWIyYTc1MGMxZDk2MGQ0YTJjMWJhOWI3YWZlYWYzY2YyZjVmNWQwY2Q5MDQ5NTBhNzMzNDQ5YjYzMCIsImludGVybmFsX3NlY3JldCI6IjE1YWNjZjc5LTQ2MWMtNDFlYi1iMjc4LTFhMzAyNTI5ZTkwMSJ9.8knfKkGxygpjf074J6dytnS3hIYtCIHHg9Dv2Q3fGEU""

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"